services:
    supra.authentication.voter.role:
        class: \Symfony\Component\Security\Core\Authorization\Voter\RoleVoter

paths:
    login:           %cms.prefix%/login
    logout:          %cms.prefix%/logout
    login_check:     %cms.prefix%/login_check
    anonymous:
        - %cms_authentication.paths.login%
        - %cms_authentication.paths.logout%
        - %cms_authentication.paths.login_check%

session:
    storage_key:  _cms_secure

users:
    shared_connection:
        host: localhost
        user: root
        password: ~
        charset: utf8
        dbname: supra9_shared_users
        driver: mysql
        event_manager: public
    user_providers:
        doctrine:
            supra.authentication.user_provider.public:
                em: public
                entity: CmsAuthentication:User
            supra.authentication.user_provider.shared:
                em: shared
                entity: CmsAuthentication:User
    provider_chain: [ doctrine.entity_managers.public, doctrine.entity_managers.shared ]
    provider_key: cms_authentication
    password_encoders:
        \Supra\Package\CmsAuthentication\Entity\User: \Supra\Package\CmsAuthentication\Encoder\SupraBlowfishEncoder
    authentication_providers:
        - supra.authentication.provider.anonymous
        - supra.authentication.provider.dao
    voters:
        - supra.authentication.voter.role
