configuration:
    prefix:         ~
routes:
    cms_authentication_login:
        pattern:            %cms_authentication.paths.login%
        controller:         CmsAuthentication:Auth:login
    cms_authentication_logout:
        pattern:            %cms_authentication.paths.logout%
        controller:         CmsAuthentication:Auth:logout
        options:
            frontend:   true
    cms_authentication_login_check:
        pattern:            %cms_authentication.paths.login_check%
        controller:         CmsAuthentication:Auth:check
        options:
            frontend:   true