configuration:
    prefix: ~
routes:
    cms_dashboard:
        pattern:            %cms.prefix%
        controller:         Cms:Dashboard:index
        options:
            frontend:       true
    cms_dashboard_applications_list:
        pattern:            %cms.prefix%/applications-list
        controller:         Cms:Dashboard:applicationsList
        options:
            frontend:       true
    cms_css_pack:
        pattern:            /_cms_resources_css_pack
        controller:         Cms:Resource:cssPack
    cms_js_pack:
        pattern:            /_cms_resources_js_pack
        controller:         Cms:Resource:jsPack
    cms_check_session:
        pattern:            %cms.prefix%/check-session
        controller:         Cms:Cms:sessionCheck
        options:
            frontend:       true

    #pages, ex content-manager
    cms_pages:
        pattern:            %cms.prefix%/content-manager
        controller:         Cms:Pages:index
        options:
            frontend:				true
    cms_pages_sitemap:
        pattern:            %cms.prefix%/content-manager/h/{params}
        requirements:
          params: ".+"
        controller:         Cms:Pages:index
    cms_pages_check_permissions:
        pattern:            %cms.prefix%/content-manager/check-permissions
        controller:         Cms:Pages:checkPermissions
    cms_pages_sitemap_pages_list:
        pattern:						%cms.prefix%/content-manager/sitemap/pages-list
        controller:					Cms:PagesSitemap:pagesList
        options:
            frontend:       true
    cms_pages_sitemap_move:
        pattern:						%cms.prefix%/content-manager/sitemap/move
        controller:					Cms:PagesSitemap:move
        options:
            frontend:       true
    cms_pages_sitemap_templates_list:
        pattern:						%cms.prefix%/content-manager/sitemap/templates-list
        controller:					Cms:PagesSitemap:templatesList
        options:
            frontend:       true
    cms_pages_sitemap_applications_list:
        pattern:						%cms.prefix%/content-manager/sitemap/applications-list
        controller:					Cms:PagesSitemap:applicationsList
        options:
            frontend:       true
    cms_pages_page_layouts:
        pattern:						%cms.prefix%/content-manager/page/layouts
        controller:					Cms:PagesPage:layoutsList
        options:
            frontend:       true
    cms_pages_page_layouts:
        pattern:						%cms.prefix%/content-manager/page/layouts
        controller:					Cms:PagesPage:layoutsList
        options:
            frontend:       true
    cms_pages_page_create:
        pattern:						%cms.prefix%/content-manager/page/create
        controller:					Cms:PagesPage:create
        options:
            frontend:       true
    cms_pages_page_delete:
        pattern:						%cms.prefix%/content-manager/page/delete
        controller:					Cms:PagesPage:delete
        options:
            frontend:       true
    cms_pages_page_copy:
        pattern:						%cms.prefix%/content-manager/page/copy
        controller:					Cms:PagesPage:copy
        options:
            frontend:       true
    cms_pages_page_localization_copy:
        pattern:						%cms.prefix%/content-manager/page/copy-localization
        controller:					Cms:PagesPage:copyLocalization
        options:
            frontend:       true
    cms_pages_page_save:
        pattern:						%cms.prefix%/content-manager/page/save
        controller:					Cms:PagesPage:save
        options:
            frontend:       true
    cms_pages_page_settings_save:
        pattern:						%cms.prefix%/content-manager/page/settings-save
        controller:					Cms:PagesPage:saveSettings
        options:
            frontend:       true
    cms_pages_template_create:
        pattern:						%cms.prefix%/content-manager/template/create
        controller:					Cms:PagesTemplate:create
        options:
            frontend:       true
    cms_pages_template_copy:
        pattern:						%cms.prefix%/content-manager/template/copy
        controller:					Cms:PagesTemplate:copy
        options:
            frontend:       true
    cms_pages_template_localization_copy:
        pattern:						%cms.prefix%/content-manager/template/copy-localization
        controller:					Cms:PagesTemplate:copyLocalization
        options:
            frontend:       true
    cms_pages_template_save:
        pattern:						%cms.prefix%/content-manager/template/save
        controller:					Cms:PagesTemplate:save
        options:
            frontend:       true
    cms_pages_template_settings_save:
        pattern:						%cms.prefix%/content-manager/template/settings-save
        controller:					Cms:PagesTemplate:saveSettings
        options:
            frontend:       true
    cms_pages_template_list:
        pattern:						%cms.prefix%/content-manager/pagesettings/templates
        controller:					Cms:PagesTemplate:templatesList
        options:
            frontend:       true
    cms_pages_group_create:
        pattern:						%cms.prefix%/content-manager/group/create
        controller:					Cms:PagesGroup:create
        options:
            frontend:       true
    cms_pages_group_save:
        pattern:						%cms.prefix%/content-manager/group/save
        controller:					Cms:PagesGroup:save
        options:
            frontend:       true
    cms_pages_group_delete:
        pattern:						%cms.prefix%/content-manager/group/delete
        controller:					Cms:PagesGroup:delete
        options:
            frontend:       true
    ## Blocks list
    cms_pages_block_list:
        pattern:						%cms.prefix%/content-manager/blocks/blocks-list
        controller:					Cms:PagesBlock:blocksList
    ## Edit Lock/Unlock
      ## HTML editor fonts list
    cms_pages_fonts_google_list:
        pattern:						%cms.prefix%/content-manager/fonts/google-fonts-list
        controller:					Cms:PagesFonts:googleFontsList
        options:
          frontend:					true
     ## Page contents get request
    cms_pages_content_get:
        pattern:						%cms.prefix%/content-manager/pagecontent/get
        controller:					Cms:PagesContent:get
        options:
          frontend:					true
    cms_pages_content_lock:
        pattern:						%cms.prefix%/content-manager/{type}/lock
        controller:					Cms:PagesContent:lock
        requirements:
          type: template|page
    cms_pages_content_unlock:
        pattern:						%cms.prefix%/content-manager/{type}/unlock
        controller:					Cms:PagesContent:unlock
        requirements:
          type: template|page
    ## Content save action
    ## @TODO: rename cms_pages_content_block_save?
    cms_pages_content_save:
        pattern:						%cms.prefix%/content-manager/pagecontent/save
        controller:					Cms:PagesContent:save
    ## Content publish action
    cms_pages_content_publish:
        pattern:						%cms.prefix%/content-manager/{type}/publish
        controller:					Cms:PagesContent:publish
        requirements:
          type: template|page
    cms_pages_content_block_insert:
        pattern:						%cms.prefix%/content-manager/pagecontent/insertblock
        controller:					Cms:PagesContent:insertBlock
    cms_pages_content_block_delete:
        pattern:						%cms.prefix%/content-manager/pagecontent/deleteblock
        controller:					Cms:PagesContent:deleteBlock
    cms_pages_content_blocks_reorder:
        pattern:						%cms.prefix%/content-manager/pagecontent/orderblocks
        controller:					Cms:PagesContent:reorderBlocks
    cms_pages_content_blocks_move:
        pattern:						%cms.prefix%/content-manager/pagecontent/moveblocks
        controller:					Cms:PagesContent:moveBlocks

    backoffice_users:
        pattern:                        %cms.prefix%/internal-user-manager
        controller:                     Cms:InternalUserManager:index
        options:
            frontend:                   true
    backoffice_user_list:
        pattern:                        %cms.prefix%/internal-user-manager/user-list
        controller:                     Cms:InternalUserManager:list
        options:
            frontend:                   true
    backoffice_user_insert:
        pattern:                        %cms.prefix%/internal-user-manager/user-insert
        controller:                     Cms:InternalUserManager:insert
        options:
            frontend:                   true
    backoffice_user_save:
        pattern:                        %cms.prefix%/internal-user-manager/user-save
        controller:                     Cms:InternalUserManager:save
        options:
            frontend:                   true
    backoffice_user_load:
        pattern:                        %cms.prefix%/internal-user-manager/user-load
        controller:                     Cms:InternalUserManager:load
        options:
            frontend:                   true
    backoffice_user_reset:
        pattern:                        %cms.prefix%/internal-user-manager/user-reset
        controller:                     Cms:InternalUserManager:reset
        options:
            frontend:                   true
    backoffice_user_delete:
        pattern:                        %cms.prefix%/internal-user-manager/user-delete
        controller:                     Cms:InternalUserManager:delete
        options:
            frontend:                   true
    backoffice_user_update:
        pattern:                        %cms.prefix%/internal-user-manager/user-update
        controller:                     Cms:InternalUserManager:update
        options:
            frontend:                   true

    media_library:
        pattern:                        %cms.prefix%/media-library
        controller:                     Cms:MediaLibrary:index
        options:
            frontend:                   true
    media_library_list:
        pattern:                        %cms.prefix%/media-library-list
        controller:                     Cms:MediaLibrary:list
        options:
            frontend:                   true
    media_library_insert:
        pattern:                        %cms.prefix%/media-library-insert
        controller:                     Cms:MediaLibrary:insert
        options:
            frontend:                   true
    media_library_delete:
        pattern:                        %cms.prefix%/media-library-delete
        controller:                     Cms:MediaLibrary:delete
        options:
            frontend:                   true
    media_library_upload:
        pattern:                        %cms.prefix%/media-library-upload
        controller:                     Cms:MediaLibrary:upload
        options:
            frontend:                   true
    media_library_view:
        pattern:                        %cms.prefix%/media-library-view
        controller:                     Cms:MediaLibrary:view
        options:
            frontend:                   true
    media_library_rotate:
        pattern:                        %cms.prefix%/media-library-rotate
        controller:                     Cms:MediaLibrary:rotate
        options:
            frontend:                   true
    media_library_crop:
        pattern:                        %cms.prefix%/media-library-crop
        controller:                     Cms:MediaLibrary:crop
        options:
            frontend:                   true
    media_library_save:
        pattern:                        %cms.prefix%/media-library-save
        controller:                     Cms:MediaLibrary:save
        options:
            frontend:                   true
    media_library_move:
        pattern:                        %cms.prefix%/media-library-move
        controller:                     Cms:MediaLibrary:move
        options:
            frontend:                   true
    media_library_download:
        pattern:                        %cms.prefix%/media-library-download/{path}
        controller:                     Cms:MediaLibrary:download
        options:
            frontend:                   true
        requirements:
            path:                       .*
        defaults:
            path:                       ~
    recycle_pages_load:
        pattern:                        %cms.prefix%/recycle/pages/load
        controller:                     Cms:Recycle:loadPages
        options:
            frontend:                   true