configuration:
    prefix: ~
routes:
    cms_dashboard:
        pattern:            %cms.prefix%
        controller:         Cms:Dashboard:index
        options:
            frontend:       true
    cms_dashboard_applications_list:
        pattern:            %cms.prefix%/applications-list
        controller:         Cms:Dashboard:applicationsList
        options:
            frontend:       true
    cms_css_pack:
        pattern:            /_cms_resources_css_pack
        controller:         Cms:Resource:cssPack
    cms_js_pack:
        pattern:            /_cms_resources_js_pack
        controller:         Cms:Resource:jsPack
    cms_check_session:
        pattern:            %cms.prefix%/check-session
        controller:         Cms:Cms:sessionCheck
        options:
            frontend:       true

    #pages, ex content-manager
    cms_pages:
        pattern:            %cms.prefix%/content-manager
        controller:         Cms:Pages:index
        options:
            frontend:				true
    cms_pages_sitemap:
        pattern:            %cms.prefix%/content-manager/h/{params}
        requirements:
          params: ".+"
        controller:         Cms:Pages:index
    cms_pages_check_permissions:
        pattern:            %cms.prefix%/content-manager/check-permissions
        controller:         Cms:Pages:checkPermissions
    cms_pages_sitemap_pages_list:
        pattern:						%cms.prefix%/content-manager/sitemap/pages-list
        controller:					Cms:PagesSitemap:pagesList
        options:
            frontend:       true
    cms_pages_sitemap_templates_list:
        pattern:						%cms.prefix%/content-manager/sitemap/templates-list
        controller:					Cms:PagesSitemap:templatesList
        options:
            frontend:       true
    cms_pages_sitemap_applications_list:
        pattern:						%cms.prefix%/content-manager/sitemap/applications-list
        controller:					Cms:PagesSitemap:applicationsList
        options:
            frontend:       true
    cms_pages_page_layouts:
        pattern:						%cms.prefix%/content-manager/page/layouts
        controller:					Cms:PagesPage:layoutsList
        options:
            frontend:       true
    cms_pages_page_layouts:
        pattern:						%cms.prefix%/content-manager/page/layouts
        controller:					Cms:PagesPage:layoutsList
        options:
            frontend:       true
    cms_pages_pagesettings_templates:
        pattern:						%cms.prefix%/content-manager/pagesettings/templates
        controller:					Cms:PagesPagesettings:templatesList
        options:
            frontend:       true
    ## Page contents get request
    cms_pages_page_get:
        pattern:						%cms.prefix%/content-manager/page/page
        controller:					Cms:PagesPage:page
    cms_pages_page_create:
        pattern:						%cms.prefix%/content-manager/page/create
        controller:					Cms:PagesPage:create
    cms_pages_template_create:
        pattern:						%cms.prefix%/content-manager/template/create
        controller:					Cms:PagesTemplate:create
    ## Blocks list
    cms_pages_block_list:
        pattern:						%cms.prefix%/content-manager/blocks/blocks-list
        controller:					Cms:PagesBlock:blocksList
    ## Edit Lock/Unlock
      ## HTML editor fonts list
    cms_pages_fonts_google_list:
        pattern:						%cms.prefix%/content-manager/fonts/google-fonts-list
        controller:					Cms:PagesFonts:googleFontsList
        options:
          frontend:					true
    cms_pages_content_lock:
        pattern:						%cms.prefix%/content-manager/{type}/lock
        controller:					Cms:PagesContent:lock
        requirements:
          type: template|page
    cms_pages_content_unlock:
        pattern:						%cms.prefix%/content-manager/{type}/unlock
        controller:					Cms:PagesContent:lock
        requirements:
          type: template|page
    ## Content save action
    ## @TODO: rename cms_pages_content_block_save?
    cms_pages_content_save:
        pattern:						%cms.prefix%/content-manager/pagecontent/save
        controller:					Cms:PagesContent:save
    ## Content publish action
    cms_pages_content_publish:
        pattern:						%cms.prefix%/content-manager/{type}/publish
        controller:					Cms:PagesContent:publish
        requirements:
          type: template|page
    cms_pages_content_block_insert:
        pattern:						%cms.prefix%/content-manager/pagecontent/insertblock
        controller:					Cms:PagesContent:insertBlock
    cms_pages_content_block_delete:
        pattern:						%cms.prefix%/content-manager/pagecontent/deleteblock
        controller:					Cms:PagesContent:deleteBlock
    cms_pages_content_blocks_reorder:
        pattern:						%cms.prefix%/content-manager/pagecontent/orderblocks
        controller:					Cms:PagesContent:reorderBlocks
    cms_pages_content_blocks_move:
        pattern:						%cms.prefix%/content-manager/pagecontent/moveblocks
        controller:					Cms:PagesContent:moveBlocks

    backoffice_users:
        pattern:                        %cms.prefix%/internal-user-manager
        controller:                     Cms:InternalUserManager:index
        options:
            frontend:                   true