configuration:
    prefix: ~
routes:
    cms_dashboard:
        pattern:            %cms.prefix%
        controller:         Cms:Dashboard:index
        options:
            frontend:       true
    cms_dashboard_applications_list:
        pattern:            %cms.prefix%/applications-list
        controller:         Cms:Dashboard:applicationsList
        options:
            frontend:       true
    cms_css_pack:
        pattern:            /_cms_resources_css_pack
        controller:         Cms:Resource:cssPack
    cms_js_pack:
        pattern:            /_cms_resources_js_pack
        controller:         Cms:Resource:jsPack
    cms_check_session:
        pattern:            %cms.prefix%/check-session
        controller:         Cms:Cms:sessionCheck
        options:
            frontend:       true

    #pages, ex content-manager
    cms_pages:
        pattern:            %cms.prefix%/content-manager
        controller:         Cms:Pages:index
        options:
            frontend:				true
    cms_pages_sitemap:
        pattern:            %cms.prefix%/content-manager/h/{params}
        requirements:
          params: ".+"
        controller:         Cms:Pages:index
    cms_pages_check_permissions:
        pattern:            %cms.prefix%/content-manager/check-permissions
        controller:         Cms:Pages:checkPermissions
    cms_pages_sitemap_pages_list:
        pattern:						%cms.prefix%/content-manager/sitemap/pages-list
        controller:					Cms:PagesSitemap:pagesList
        options:
            frontend:       true
    cms_pages_sitemap_templates_list:
        pattern:						%cms.prefix%/content-manager/sitemap/templates-list
        controller:					Cms:PagesSitemap:templatesList
        options:
            frontend:       true
    cms_pages_sitemap_applications_list:
        pattern:						%cms.prefix%/content-manager/sitemap/applications-list
        controller:					Cms:PagesSitemap:applicationsList
        options:
            frontend:       true
    cms_pages_page_layouts:
        pattern:						%cms.prefix%/content-manager/page/layouts
        controller:					Cms:PagesPage:layoutsList
        options:
            frontend:       true
    cms_pages_page_layouts:
        pattern:						%cms.prefix%/content-manager/page/layouts
        controller:					Cms:PagesPage:layoutsList
        options:
            frontend:       true
    cms_pages_pagesettings_templates:
        pattern:						%cms.prefix%/content-manager/pagesettings/templates
        controller:					Cms:PagesPagesettings:templatesList
        options:
            frontend:       true
    cms_pages_page_page:
        pattern:						%cms.prefix%/content-manager/page/page
        controller:					Cms:PagesPage:page
        options:
            frontend:       true
    cms_pages_page_lock:
        pattern:						%cms.prefix%/content-manager/page/lock
        controller:					Cms:PagesPage:lock
    cms_pages_page_unlock:
        pattern:						%cms.prefix%/content-manager/page/unlock
        controller:					Cms:PagesPage:unlock
    cms_pages_block_list:
        pattern:						%cms.prefix%/content-manager/blocks/blocks-list
        controller:					Cms:PagesBlock:blocksList