services:
    locale.manager:
        class: \Supra\Core\Locale\LocaleManager
    locale.detector.cookie:
        class: \Supra\Core\Locale\Detector\CookieDetector
    locale.detector.path:
        class: \Supra\Core\Locale\Detector\PathDetector
    locale.storage.cookie:
        class: \Supra\Core\Locale\Storage\CookieStorage
    supra.doctrine.event_subscriber.table_name_prefixer:
        class: \Supra\Core\Doctrine\Subscriber\TableNamePrefixer
        parameters: ['su_', '']
    supra.doctrine.event_subscriber.detached_discriminator_handler:
        class: \Supra\Core\Doctrine\Subscriber\DetachedDiscriminatorHandler
    supra.doctrine.event_subscriber.nested_set_listener:
        class: \Supra\Core\NestedSet\Listener\NestedSetListener
    supra.doctrine.event_subscriber.timestampable:
        class: \Supra\Package\Framework\Doctrine\Subscriber\TimestampableListener
    supra.framework.session_storage_native:
        class: \Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage
        parameters: [[], "@supra.framework.session_handler_doctrine"]
    supra.framework.session_handler_doctrine:
        class: \Supra\Package\Framework\Session\DoctrineSessionHandler
locales:
    locales:
        -
            id: en
            title: English
            country: Latvia
            properties:
               flag: en
               language: en
            active: true
    detectors:
        - locale.detector.cookie
    ## @FIXME: Doesn't work now, requires Response object
    ##locale_storage:
    ##    - locale.storage.cookie
    storage: ~
    current: en
doctrine:
    credentials:
        hostname: localhost
        username: root
        password: ~
        charset: utf8
        database: supra9
    event_managers:
        public:
            subscribers:
                - supra.doctrine.event_subscriber.table_name_prefixer
                - supra.doctrine.event_subscriber.detached_discriminator_handler
                - supra.doctrine.event_subscriber.nested_set_listener
                - supra.doctrine.event_subscriber.timestampable
    configurations:
        default:
            hydrators:
                - [ColumnHydrator, \Supra\Core\Doctrine\Hydrator\ColumnHydrator]
    types:
        - [supraId20,  \Supra\Core\Doctrine\Type\SupraIdType]
        - [path, \Supra\Core\Doctrine\Type\PathType]
    type_overrides:
        - [array, \Supra\Core\Doctrine\Type\ArrayType]
    connections:
        default:
            host: %framework.doctrine.credentials.hostname%
            user: %framework.doctrine.credentials.username%
            password: %framework.doctrine.credentials.password%
            dbname: %framework.doctrine.credentials.database%
            charset: %framework.doctrine.credentials.charset%
            driver: mysql
            event_manager: public
    entity_managers:
        public:
            connection: default
            event_manager: public
    default_entity_manager: public
    default_connection: default
session:
    storage: supra.framework.session_storage_native
