configuration:
    prefix:             ~
routes:
    framework_combo:
        pattern:        /_framework_internal/combo/{paths}
        controller:     Framework:Combo:combo
        requirements:
            paths:      .+
        defaults:
            paths:      ~
    framework_routes:
        pattern:        /_framework_internal/routes
        controller:     Framework:Routing:export
